### ISSUE TITLE
Next Steps for Manuscript – Task List

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/ec1-aquatic-geochemistry-paper#2]
- [ ] Download the spatial data we discussed in the breakout to this [folder](https://drive.google.com/drive/folders/1_eS6LjitViueRyC4SZ9DZBQiDT2YrPkp?usp=sharing), and provide links to how we have accessed these datasets in [this spreadsheet](https://docs.google.com/spreadsheets/d/1SCQipw5gqhLlC3m3MMwklDpdgYI2uJ4OwyjZkNFR3jc/edit?usp=sharing). @opalotenburg @kkhomolka
- [ ] Follow up group discussion is likely needed as we move toward analyzing these, perhaps in QGIS as we discussed in the breakout. 
- [ ] **All:** Please slack lead and corresponding authors if you’re interested in participating in the spatial data analysis!
- [ ] @stephpenn1 @amyerspigg create multivariate exploratory plots using surface water datasets and kit metadata
- [x] re-run matlab script for non-normalized CDOM datasets and reupload to G-Drive
